name: Test

on:
  push:
    branches:
      - *
    paths:
      - "**/*.go"
      - "**/*.yaml"
      - "**/*.sh"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/test.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/test.yml"

env:
  GO_VERSION: 1.19

jobs:
  test-win:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - name: Set up Go 1.x.y
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Test
        run: |
          go mod verify
          go mod download
          go test -v -gcflags "all=-l" ./pkg/object/mqttproxy/...
